[package]
name = "gameengine"
version = "0.1.0"
edition = "2021"

[lib]
name = "gameengine"
path = "src/lib.rs" 

[[bin]]
name = "gameengine-bin"
path = "src/main.rs"

[dependencies]
bytemuck = "1.19.0"
chrono = "0.4.38"
clap = "4.5.21"
config = "0.14.1"
dirs = "5.0.1"
fern = "0.7.0"
gtk4 = "0.9.3"
gdk4 = "0.9.3"
gdk4-x11 = "0.9.3"
gdk4-wayland = "0.9.3"
glib = "0.20.6"
log = "0.4.22"
mlua = { version = "0.10.1", features = ["lua54"] }
once_cell = "1.20.2"
raw-window-handle = "0.6.2"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
toml = "0.8.19"
vulkano = "0.34.1"
winit = { version = "0.30.5", features = ["x11", "wayland"] }
