[package]
name = "gameengine"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = "4.5.20"
config = "0.14.1"
dirs = "5.0.1"
fern = "0.7.0"
gtk4 = "0.9.2"
gdk4 = "0.9.2"
glib = "0.20.4"
log = "0.4.22"
mlua = { version = "0.10.0", features = ["lua54"] }
once_cell = "1.20.2"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
toml = "0.8.19"
wgpu = "23.0.0"
winit = "0.30.5"
